Repository cakephp/migrations, pull requests merged in 2020-04, with the labels that each got.

#437 4.x shells
  src/Command/BakeMigrationDiffCommand.php
  src/Command/BakeMigrationSnapshotCommand.php
  src/Command/BakeSimpleMigrationCommand.php
  src/Command/MigrationsCommand.php
  src/Command/SnapshotTrait.php
  src/Shell/Task/SnapshotTrait.php
  tests/Fixture/EventsFixture.php
  tests/TestCase/Command/BakeMigrationCommandTest.php
  tests/TestCase/Command/BakeMigrationDiffCommandTest.php
  tests/TestCase/Command/BakeMigrationSnapshotCommandTest.php
  tests/TestCase/Command/BakeSeedCommandTest.php
  tests/TestCase/Command/CreateTest.php
  tests/TestCase/Command/DumpTest.php
  tests/TestCase/Command/TestClassWithSnapshotTrait.php
  tests/TestCase/MigrationsTest.php
  tests/TestCase/Shell/TestCompletionStringOutput.php
  tests/bootstrap.php
  tests/test_app/App/Command/CustomBakeMigrationDiffCommand.php
  tests/test_app/App/Command/CustomRemoveBakeMigrationDiffCommand.php
  tests/test_app/App/Command/CustomSimpleBakeMigrationDiffCommand.php
Labels: bake

#444 Add IdeHelper suggest
  composer.json
  docs/en/index.rst
Labels: Documentation

#457 Add column length guessing for tiny and small.
  src/Util/ColumnParser.php
  tests/TestCase/Command/BakeMigrationCommandTest.php
Labels: enhancement
